apiVersion: v1
kind: ConfigMap
metadata:
  name: vcloud-ccm-configmap
  namespace: kube-system
data:
  vcloud-ccm-config.yaml: |+
    vcd:
      host: "https://bos1-vcloud-static-177-114.eng.vmware.com"
      org: "tenant1"
      vdc: "tenant1_ovdc"
      network: "tenant1_routed_ovdc_nw"
      vipSubnet: "10.150.191.253/19"
    loadbalancer:
      oneArm:
        startIP: "192.168.8.2"
        endIP: "192.168.8.100"
      ports:
        http: 80
        https: 443
      certAlias: "test"
    clusterid: "123456"
immutable: true
